import { EntityManager } from 'typeorm';

const addresses = {
  LINKEDIN: { name: 'LinkedIn Ave', address: '123 LinkedIn Ave, Mountain View, CA 94043' },
  FACEBOOK: { name: 'Facebook Blvd', address: '456 Facebook Blvd, Menlo Park, CA 94025' },
  QONTO: { name: 'Qonto Rd', address: '789 Qonto Rd, Paris, France 75009' },
  MICROSOFT: { name: 'Microsoft Way', address: '101 Microsoft Way, Redmond, WA 98052' },
  AIRBNB: { name: 'Airbnb St', address: '202 Airbnb St, San Francisco, CA 94103' },
  GOOGLE: { name: 'Google Dr', address: '303 Google Dr, Mountain View, CA 94043' },
  NETFLIX: { name: 'Netflix Ln', address: '404 Netflix Ln, Los Gatos, CA 95032' },
  LIBEO: { name: 'Libeo Blvd', address: '505 Libeo Blvd, Paris, France 75002' },
  CLAAP: { name: 'Claap St', address: '606 Claap St, London, UK WC2N 5DU' },
  HASURA: { name: 'Hasura Rd', address: '707 Hasura Rd, San Francisco, CA 94105' },
  WEWORK: { name: 'Wework Way', address: '808 Wework Way, New York, NY 10011' },
  SAMSUNG: { name: 'Samsung St', address: '909 Samsung St, Seoul, South Korea 04520' },
  ALGOLIA: { name: 'Algolia Blvd', address: '1010 Algolia Blvd, Paris, France 75008' },
};

const tableName = 'company';

export const DEV_SEED_COMPANY_IDS = {
  LINKEDIN: '20202020-3ec3-4fe3-8997-b76aa0bfa408',
  FACEBOOK: '20202020-5d81-46d6-bf83-f7fd33ea6102',
  QONTO: '20202020-0713-40a5-8216-82802401d33e',
  MICROSOFT: '20202020-ed89-413a-b31a-962986e67bb4',
  AIRBNB: '20202020-171e-4bcc-9cf7-43448d6fb278',
  GOOGLE: '20202020-c21e-4ec2-873b-de4264d89025',
  NETFLIX: '20202020-707e-44dc-a1d2-30030bf1a944',
  LIBEO: '20202020-3f74-492d-a101-2a70f50a1645',
  CLAAP: '20202020-cfbf-4156-a790-e39854dcd4eb',
  HASURA: '20202020-f86b-419f-b794-02319abe8637',
  WEWORK: '20202020-5518-4553-9433-42d8eb82834b',
  SAMSUNG: '20202020-f79e-40dd-bd06-c36e6abb4678',
  ALGOLIA: '20202020-1455-4c57-afaf-dd5dc086361d',
};

export const seedCompanies = async (
  entityManager: EntityManager,
  schemaName: string,
) => {
  await entityManager
    .createQueryBuilder()
    .insert()
    .into(`${schemaName}.${tableName}`, [
      'id',
      'name',
      'domainName',
      'employees',
      'linkedinLink',
      'xLink',
      'annualRecurringRevenue',
      'address',
      'idealCustomerProfile',
      'position',
    ])
    .orIgnore()
    .values([
      {
        id: DEV_SEED_COMPANY_IDS.LINKEDIN,
        name: 'Linkedin',
        domainName: 'linkedin.com',
        employees: 15000,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://x.com/linkedin', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 1000000, currencyCode: 'USD' }),
        address: JSON.stringify(addresses.LINKEDIN),
        idealCustomerProfile: true,
        position: 1,
      },
      {
        id: DEV_SEED_COMPANY_IDS.FACEBOOK,
        name: 'Facebook',
        domainName: 'facebook.com',
        employees: 45000,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/facebook', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/facebook', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 10000000, currencyCode: 'USD' }),
        address: JSON.stringify(addresses.FACEBOOK),
        idealCustomerProfile: true,
        position: 2,
      },
      {
        id: DEV_SEED_COMPANY_IDS.QONTO,
        name: 'Qonto',
        domainName: 'qonto.com',
        employees: 500,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/qonto', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/qonto', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 5000000, currencyCode: 'EUR' }),
        address: JSON.stringify(addresses.QONTO),
        idealCustomerProfile: true,
        position: 3,
      },
      {
        id: DEV_SEED_COMPANY_IDS.MICROSOFT,
        name: 'Microsoft',
        domainName: 'microsoft.com',
        employees: 180000,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/microsoft', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/microsoft', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 150000000, currencyCode: 'USD' }),
        address: JSON.stringify(addresses.MICROSOFT),
        idealCustomerProfile: true,
        position: 4,
      },
      {
        id: DEV_SEED_COMPANY_IDS.AIRBNB,
        name: 'Airbnb',
        domainName: 'airbnb.com',
        employees: 14000,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/airbnb', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/airbnb', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 3000000, currencyCode: 'USD' }),
        address: JSON.stringify(addresses.AIRBNB),
        idealCustomerProfile: true,
        position: 5,
      },
      {
        id: DEV_SEED_COMPANY_IDS.GOOGLE,
        name: 'Google',
        domainName: 'google.com',
        employees: 135000,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/google', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/google', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 160000000, currencyCode: 'USD' }),
        address: JSON.stringify(addresses.GOOGLE),
        idealCustomerProfile: true,
        position: 6,
      },
      {
        id: DEV_SEED_COMPANY_IDS.NETFLIX,
        name: 'Netflix',
        domainName: 'netflix.com',
        employees: 9400,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/netflix', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/netflix', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 250000000, currencyCode: 'USD' }),
        address: JSON.stringify(addresses.NETFLIX),
        idealCustomerProfile: true,
        position: 7,
      },
      {
        id: DEV_SEED_COMPANY_IDS.LIBEO,
        name: 'Libeo',
        domainName: 'libeo.io',
        employees: 200,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/libeo', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/libeo', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 1200000, currencyCode: 'EUR' }),
        address: JSON.stringify(addresses.LIBEO),
        idealCustomerProfile: true,
        position: 8,
      },
      {
        id: DEV_SEED_COMPANY_IDS.CLAAP,
        name: 'Claap',
        domainName: 'claap.io',
        employees: 50,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/claap', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/claap', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 900000, currencyCode: 'GBP' }),
        address: JSON.stringify(addresses.CLAAP),
        idealCustomerProfile: true,
        position: 9,
      },
      {
        id: DEV_SEED_COMPANY_IDS.HASURA,
        name: 'Hasura',
        domainName: 'hasura.io',
        employees: 500,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/hasura', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/hasura', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 5000000, currencyCode: 'USD' }),
        address: JSON.stringify(addresses.HASURA),
        idealCustomerProfile: true,
        position: 10,
      },
      {
        id: DEV_SEED_COMPANY_IDS.WEWORK,
        name: 'Wework',
        domainName: 'wework.com',
        employees: 12000,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/wework', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/wework', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 3000000, currencyCode: 'USD' }),
        address: JSON.stringify(addresses.WEWORK),
        idealCustomerProfile: true,
        position: 11,
      },
      {
        id: DEV_SEED_COMPANY_IDS.SAMSUNG,
        name: 'Samsung',
        domainName: 'samsung.com',
        employees: 287000,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/samsung', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/samsung', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 220000000, currencyCode: 'KRW' }),
        address: JSON.stringify(addresses.SAMSUNG),
        idealCustomerProfile: true,
        position: 12,
      },
      {
        id: DEV_SEED_COMPANY_IDS.ALGOLIA,
        name: 'Algolia',
        domainName: 'algolia.com',
        employees: 500,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/algolia', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/algolia', label: 'Twitter' }),
        annualRecurringRevenue: JSON.stringify({ amountMicros: 5000000, currencyCode: 'EUR' }),
        address: JSON.stringify(addresses.ALGOLIA),
        idealCustomerProfile: true,
        position: 13,
      },
    ])
    .execute();
};
