import { EntityManager } from 'typeorm';

import { DEV_SEED_COMPANY_IDS } from 'src/database/typeorm-seeds/workspace/companies';

const tableName = 'person';

export const DEV_SEED_PERSON_IDS = {
  CHRISTOPH: '20202020-1c0e-494c-a1b6-85b1c6fefaa5',
  SYLVIE: '20202020-ac73-4797-824e-87a1f5aea9e0',
  CHRISTOPHER_G: '20202020-f517-42fd-80ae-14173b3b70ae',
  ASHLEY: '20202020-eee1-4690-ad2c-8619e5b56a2e',
  NICHOLAS: '20202020-6784-4449-afdf-dc62cb8702f2',
  ISABELLA: '20202020-490f-4466-8391-733cfd66a0c8',
  MATTHEW: '20202020-80f1-4dff-b570-a74942528de3',
  ELIZABETH: '20202020-338b-46df-8811-fa08c7d19d35',
  CHRISTOPHER_N: '20202020-64ad-4b0e-bbfd-e9fd795b7016',
  AVERY: '20202020-5d54-41b7-ba36-f0d20e1417ae',
  ETHAN: '20202020-623d-41fe-92e7-dd45b7c568e1',
  MADISON: '20202020-2d40-4e49-8df4-9c6a049190ef',
  BERTRAND: '20202020-2d40-4e49-8df4-9c6a049190df',
  LOUIS: '20202020-2d40-4e49-8df4-9c6a049191de',
  LORIE: '20202020-2d40-4e49-8df4-9c6a049191df',
};

export const seedPeople = async (
  entityManager: EntityManager,
  schemaName: string,
) => {
  await entityManager
    .createQueryBuilder()
    .insert()
    .into(`${schemaName}.${tableName}`, [
      'id',
      'name',
      'phone',
      'city',
      'email',
      'jobTitle',
      'position',
      'linkedinLink',
      'xLink',
      'avatarUrl',
      'companyId',
    ])
    .orIgnore()
    .values([
      {
        id: DEV_SEED_PERSON_IDS.CHRISTOPH,
        name: JSON.stringify({ firstName: 'Christoph', lastName: 'Callisto' }),
        phone: '+33789012345',
        city: 'Seattle',
        email: 'christoph.calisto@linkedin.com',
        jobTitle: 'Software Engineer',
        position: 1,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/christoph', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/christoph', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.LINKEDIN,
      },
      {
        id: DEV_SEED_PERSON_IDS.SYLVIE,
        name: JSON.stringify({ firstName: 'Sylvie', lastName: 'Palmer' }),
        phone: '+33780123456',
        city: 'Los Angeles',
        email: 'sylvie.palmer@linkedin.com',
        jobTitle: 'Product Manager',
        position: 2,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/sylvie', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/sylvie', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.LINKEDIN,
      },
      {
        id: DEV_SEED_PERSON_IDS.CHRISTOPHER_G,
        name: JSON.stringify({ firstName: 'Christopher', lastName: 'Gonzalez' }),
        phone: '+33789012345',
        city: 'Seattle',
        email: 'christopher.gonzalez@qonto.com',
        jobTitle: 'Marketing Specialist',
        position: 3,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/christopher_g', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/christopher_g', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.QONTO,
      },
      {
        id: DEV_SEED_PERSON_IDS.ASHLEY,
        name: JSON.stringify({ firstName: 'Ashley', lastName: 'Parker' }),
        phone: '+33780123456',
        city: 'Los Angeles',
        email: 'ashley.parker@qonto.com',
        jobTitle: 'Designer',
        position: 4,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/ashley', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/ashley', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.QONTO,
      },
      {
        id: DEV_SEED_PERSON_IDS.NICHOLAS,
        name: JSON.stringify({ firstName: 'Nicholas', lastName: 'Wright' }),
        phone: '+33781234567',
        city: 'Seattle',
        email: 'nicholas.wright@microsoft.com',
        jobTitle: 'Data Scientist',
        position: 5,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/nicholas', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/nicholas', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.MICROSOFT,
      },
      {
        id: DEV_SEED_PERSON_IDS.ISABELLA,
        name: JSON.stringify({ firstName: 'Isabella', lastName: 'Scott' }),
        phone: '+33782345678',
        city: 'New York',
        email: 'isabella.scott@microsoft.com',
        jobTitle: 'Project Manager',
        position: 6,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/isabella', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/isabella', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.MICROSOFT,
      },
      {
        id: DEV_SEED_PERSON_IDS.MATTHEW,
        name: JSON.stringify({ firstName: 'Matthew', lastName: 'Green' }),
        phone: '+33783456789',
        city: 'Seattle',
        email: 'matthew.green@microsoft.com',
        jobTitle: 'Engineer',
        position: 7,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/matthew', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/matthew', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.MICROSOFT,
      },
      {
        id: DEV_SEED_PERSON_IDS.ELIZABETH,
        name: JSON.stringify({ firstName: 'Elizabeth', lastName: 'Baker' }),
        phone: '+33784567890',
        city: 'New York',
        email: 'elizabeth.baker@airbnb.com',
        jobTitle: 'Sales Manager',
        position: 8,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/elizabeth', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/elizabeth', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.AIRBNB,
      },
      {
        id: DEV_SEED_PERSON_IDS.CHRISTOPHER_N,
        name: JSON.stringify({ firstName: 'Christopher', lastName: 'Nelson' }),
        phone: '+33785678901',
        city: 'San Francisco',
        email: 'christopher.nelson@airbnb.com',
        jobTitle: 'Operations Manager',
        position: 9,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/christopher_n', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/christopher_n', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.AIRBNB,
      },
      {
        id: DEV_SEED_PERSON_IDS.AVERY,
        name: JSON.stringify({ firstName: 'Avery', lastName: 'Carter' }),
        phone: '+33786789012',
        city: 'New York',
        email: 'avery.carter@airbnb.com',
        jobTitle: 'Designer',
        position: 10,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/avery', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/avery', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.AIRBNB,
      },
      {
        id: DEV_SEED_PERSON_IDS.ETHAN,
        name: JSON.stringify({ firstName: 'Ethan', lastName: 'Mitchell' }),
        phone: '+33787890123',
        city: 'Los Angeles',
        email: 'ethan.mitchell@google.com',
        jobTitle: 'Engineer',
        position: 11,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/ethan', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/ethan', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.GOOGLE,
      },
      {
        id: DEV_SEED_PERSON_IDS.MADISON,
        name: JSON.stringify({ firstName: 'Madison', lastName: 'Perez' }),
        phone: '+33788901234',
        city: 'Seattle',
        email: 'madison.perez@google.com',
        jobTitle: 'Marketing Specialist',
        position: 12,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/madison', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/madison', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.GOOGLE,
      },
      {
        id: DEV_SEED_PERSON_IDS.BERTRAND,
        name: JSON.stringify({ firstName: 'Bertrand', lastName: 'Voulzy' }),
        phone: '+33788901234',
        city: 'Seattle',
        email: 'bertrand.voulzy@google.com',
        jobTitle: 'Designer',
        position: 13,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/bertrand', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/bertrand', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.GOOGLE,
      },
      {
        id: DEV_SEED_PERSON_IDS.LOUIS,
        name: JSON.stringify({ firstName: 'Louis', lastName: 'Duss' }),
        phone: '+33788901234',
        city: 'Seattle',
        email: 'louis.duss@google.com',
        jobTitle: 'Engineer',
        position: 14,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/louis', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/louis', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.GOOGLE,
      },
      {
        id: DEV_SEED_PERSON_IDS.LORIE,
        name: JSON.stringify({ firstName: 'Lorie', lastName: 'Vladim' }),
        phone: '+33788901235',
        city: 'Seattle',
        email: 'lorie.vladim@google.com',
        jobTitle: 'Sales Manager',
        position: 15,
        linkedinLink: JSON.stringify({ url: 'http://linkedin.com/lorie', label: 'LinkedIn' }),
        xLink: JSON.stringify({ url: 'http://twitter.com/lorie', label: 'Twitter' }),
        avatarUrl: 'https://picsum.photos/200/300',
        companyId: DEV_SEED_COMPANY_IDS.GOOGLE,
      },
    ])
    .execute();
};
